version: "3"

services:
  db:
    image: mysql:5.7
    volumes:
      - $PWD/docker/mysql/init:/docker-entrypoint-initdb.d:delegated
      - $PWD/docker/mysql/conf/my.cnf:/etc/mysql/conf.d/my.cnf:delegated
      - $PWD/docker/mysql/data:/var/lib/mysql:delegated
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
  web:
    build:
      context: ./docker/php-apache
      dockerfile: Dockerfile
    volumes:
      - $PWD/ec-cube3:/var/www/html:delegated
    ports:
      - 8080:80
    depends_on:
      - db
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=db
      - PMA_USER=root
      - PMA_PASSWORD=root
    ports:
      - 8081:80
    depends_on:
      - db
